language: php

php:
  - 7.1
  - 7.2

before_script:
  - phpenv config-rm xdebug.ini
  - composer config github-oauth.github.com ${COMPOSER_TOKEN}
  - composer install --no-interaction
  - ./init.sh

script:
  - vendor/bin/phpunit

matrix:
  include:
    - php: 5.6
      env: dependencies=lowest
  allow_failures:
    - php: 5.6
